name: bancocentralbrasil
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install codecov

    - name: Run Tests
      run: |
        python -m unittest

    - name: Run coverage
      run: |
        python -m coverage run --source=bc tests/test_bancocentral.py
        codecov